name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Build backend image
      - name: Build backend Docker image
        run: docker build -t pxtn/h2o-backend -f ./Server/Dockerfile ./Server

      # Build frontend image
      - name: Build frontend Docker image
        run: docker build -t pxtn/h2o-frontend -f ./client/Dockerfile ./client

      # Push backend image to Docker Hub
      - name: Push backend image to Docker Hub
        run: docker push pxtn/h2o-backend:latest

      # Push frontend image to Docker Hub
      - name: Push frontend image to Docker Hub
        run: docker push pxtn/h2o-frontend:latest

  deploy:
    needs: build
    runs-on: [aws-h2o]
    steps:
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo service docker start

      - name: Check Docker version
        run: docker --version

      - name: Create Docker network
        run: docker network create h2o-network || true

      - name: Pull backend image from Docker Hub
        run: docker pull pxtn/h2o-backend:latest

      - name: Pull frontend image from Docker Hub
        run: docker pull pxtn/h2o-frontend:latest

      - name: Delete old backend container
        run: docker rm -f h2o-backend-container || true

      - name: Delete old frontend container
        run: docker rm -f h2o-frontend-container || true

      - name: Delete old container
        run: docker rm -f h2o-app-container || true

      # Run backend container
      - name: Run backend Docker container
        run: |
          docker run -d \
          --network h2o-network \
          -p 3001:3000 \
          --name h2o-backend-container \
          -e MONGODB_URL="mongodb+srv://patnattapong1:sIsEdapY3eBIo9Qj@cluster0.1qyztlj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" \
          -e CLIENT_URL="http://h2o-frontend-container:5174/" \
          -e PORT="3000" \
          -e SECRET="H2O-Project" \
          -e ACCESS_TOKEN_SECRET="879a8c742a4091c29ca1c749a4ff61eedd5e1626d1ed6810e93eb496892ae57591b62ecdd8433c8f0d9a765b69614643d94ceb086256654dcc5647adadbe1533" \
          -e HOST="smtp.gmail.com" \
          -e SERVICE="gmail" \
          -e EMAIL_PORT="587" \
          -e SECURE="true" \
          -e USER="644259012@webmail.npru.ac.th" \
          -e PASS="Pns21092545" \
          -e STRIPE_SECRET_KEY="sk_test_51PpB0zDTXPppEslSifpqM4p70gblHZDHt6mGBJKmAlZ5GoCt0zQ8ldFHpFug00j0qARjdoGstEuyqXTKrMDBaACh006nlNNVEK" \
          pxtn/h2o-backend

      # Run frontend container
      - name: Run frontend Docker container
        run: |
          docker run -d \
          --network h2o-network \
          -p 80:80 \
          --name h2o-frontend-container \
          -e VITE_H2O_URL="http://h2o-backend-container:3000/" \
          pxtn/h2o-frontend
